### ISSUE TITLE
[fix] 프로필 라우팅 관련

### ISSUE THREAD

**Issue by sjgaru-dev** [Dev-FE-1/Toy_Project_3_Team1#97]
### 🐞 설명

- [x] profile/${id}  없는 id 도 404로 리다이렉트 되지 않음 (수정함)
2. id의 대소문자 구분여부 
- [x] 다른 사람 프로필 페이지 이동 후 하단네비로 내 프로필 클릭 시, URL은 변경되나 화면이 바뀌지 않음. (수정함)
- [x] 구글 로그인 시 홈으로 이동하지 않음 / 로그인 한 상태에서 로그인 화면 접속이 가능함 (수정함)

### 💻 버그 시뮬레이션

![image](https://github.com/user-attachments/assets/852f9df0-4d82-4490-8144-17a6c0a49f2e)

**Comment by jizerozz** [comment]
@sjgaru-dev 
다른 사람 프로필 페이지 이동 후 하단네비로 내 프로필 클릭 시, URL은 변경되나 화면이 바뀌지 않음 
이 부분은 제가 해결해두었습니다!!
